### PR TITLE
Add _hulls property to allow a bmodel to set for which hulls it should have clipnodes

### LINKED ISSUE #418: [Feature] _illusionary on any entity to disable collision (like ZHLT's zhlt_noclip)
Allows for stuff like non-solid trains and doors for aesthetic purposes (ex: clouds), without requiring mod support. Also saves clipnodes on non-standard nonsolid entities.

In Q1/Hx2/HL1, this would only generate hull 0 for any brush that isn't a clip brush. In Q2, this wouldn't really be necessary unless making a gigantic map (since contents_mist exists), but would only generate the visual mesh.

### PR DESCRIPTION
**Pull request by L-P**
Fixes #418.

### CODE REVIEW

**Comment by L-P** [comment]
Went for a more generic solution than the original `_illusionary`.  
Hulls can be set using a Flags property, one bit per hull. Default is 0, enables all hulls.

**Comment by ericwa** [comment]
Thanks, looks good. I fixed `"_hulls" "6"` (i.e. generate hull 1 and 2 only) - it was letting me walk through (Quakespasm) until I adjusted it to generate the placeholder empty hull 0.

**Comment by SirYodaJedi** [comment]
Finally got around to reading these commits.

Since `0` is the default behavior of emitting all hulls, how are you supposed to only emit the point hull (nominally 0)? Do you just have to put a bogus value like 16?

Also, if you put `_hulls` on worldspawn, do bmodels without `_hulls` inherit?

**Comment by ericwa** [comment]
`1` should emit only the point hull, because it's interpreted as `0b001` and reading from right to left, the lowest set bit means "emit hull0", and the next two unset bits mean "don't emit hull1", "don't emit hull2".

I don't think it'll inherit from worldspawn to bmodels; we don't do that automatically but only for certain keys (dirt, minlight, etc.).

I'm not 100% sure if it'll work on worldspawn but it should, but it won't work on "fake" bmodels like func_group, func_detail, etc.

**Pull request merged**
