### PR TITLE
vis algorithm improvement (2h42 -> 57m on ad_dm5)

### PR DESCRIPTION
**Pull request by rrika**
I have developed a bounded-overhead method to further reduce work in the recursive vis process and ported it to ericw-vis. It has one tweakable which this patch exposes via command-line argument -targetchecks, where "-targetchecks 0" corresponds to the usual behavior, and "-targetchecks 1" will at most double vis time.

Different maps respond differently well:
- Very simple maps ones are slowed down: ad_e1m1 runtime increases by 23% (targetchecks=1, 43s -> 53s) though that's still less than the theoretical 100% increase.
- On a more complex map (E3M5-test) runtime decreases slightly by 10% (targetchecks=0.4, 58s -> 52s)
- On very complex maps (ad_dm5) runtime can decrease by 60% (targetchecks=0.45 2h42 -> 57m)

The X axis in this chart is the "-targetchecks" setting, Y axis is runtime:
Screenshot_2023-06-18_22-28-38

The idea is to check portal visibilities directly instead of brute-forcing every single path towards it. If a portal isn't even visible when ignoring the ones between the current source/pass and itself, then it certainly won't be with all the portals in-between. The number of targets (mightsee & ~vis) is in the hundreds though, while the number of portals leading out of a leaf is ~5. So target checks are not affordable at every single step.
This patch counts the number of adjacent portals processed and compares it to the number of targets. It can then occasionally trigger target checks while keeping a ratio of adjacent and target portal checks, thus bounding the overhead.

The code has been ported three times (my own vis → hlvis → ericw-vis(master) → ericw-vis(brushbsp)) so some bugs might've snuck in. In doubt, the code in TargetChecks should mirror the one in RecursiveLeafFlow.

One artifact of this is that the original version expected mighsee to be indexed by portal instead of leaf. Thus nummightsee was a number of portals and numExpectedTargetChecks as well. This number was then compared with numSteps (also a number of portals) and all was fine.
In this version, nummightsee is a count of leafs, so the condition to call IterativeTargetChecks is comparing different units. This is fine however since the counters are later updated with numActualTargetChecks which is in portals again.

I understand I sent this PR is out of the blue, so it you don't feel confident reviewing it or consider it out of scope for your project that's fine too. I'm happy to explain more or make adjustments.

### CODE REVIEW

**Comment by Paril** [comment]
Cool. I do like the concept, and any time saved on vis is a good thing. I'd still prefer map authors just detail properly though, vis can be reduced to less than a second on pretty much any map if you're careful with how you do things, but if this doesn't introduce any false positives or false negatives and only has a minute impact on smaller maps it's probably something we can enable automatically if the map appears too complex or something.

**Comment by Paril** [comment]
Hey hey.

I haven't had time to look closely at this, but basically what I wanted to do at some point was run a test suite on a bunch of maps and just make sure that the vis data ends up being identical between all of them. That's the only hang-up really. Once I can confirm that, I have no problem merging it.

I'll be busy until next Thursday, but if you wanted to do this while I'm away, basically just grab a crapload of map files that you can find (for both Q1 and Q2; if you can't do Q2 easily I can do that later), compile them, and just hash the vis data & make sure it's identical in size and hash.

**Comment by rrika** [comment]
I can not 100% be sure the data will be the same. At least when experimenting with hlvis I found that sometimes the recursive_leaf_flow will continue with NaNs in the windings, so earlier pruning of search space leads to different results. I'll still try to do this and see how big the difference is.

I was interested in #289 because it would mean only bsp files are needed for this validation, not map files.

I was wondering whether it makes sense to use a raytracer for validation. Shoot a ray, and see if it is indeed visible in the PVS.

**Comment by Paril** [comment]
Generating a PRT from a BSP would be interesting but I'm not sure exactly how it would work with all of the weird stuff we have going on like illusionary visblockers.

NaN's being in windings definitely sounds like a bug, but it should be possible to track down where the nan first comes from. We've not had that issue in our codebase (vis is deterministic for us afaik).

For validation, the only way we can really verify that it's correct is if the same leaves are visible from the same other leaf, which is basically just a memcmp on the whole lump anyways. If there's any difference in that output, there's the potential for a false positive or a false negative - I'd rather it be a false positive than a false negative, though

**Comment by rrika** [comment]
I see… (regarding illusionary visblockers)

Note that determinism doesn't mean you don't have NaNs because NaNs are deterministic. Vis is deterministic with thread-count 1 in my experience.

Do you know a quake engine that can be easily rigged to render the scene from given positions and store some screenshots? That could be done for every leaf with a differing vis bit.

**Comment by rrika** [comment]
Okay, I'm now more convinced .map files are the easier way, but here's one last stab at it: if a rerun of classical vis on a reconstructed prt gives the same results as already in the file, then it is probably not using illusionary visblockers.

**Comment by Paril** [comment]
To be honest it'd be easier for our test suite if it was .map's anyways since we tend to run qbsp/vis/light in sequence for all of them anyhow.

**Comment by rrika** [comment]
I haven't gotten around to setting up tests but maybe this weekend

**Comment by ericwa** [comment]
Hey, sorry for the long delay. I just pushed a small change to use C++20 `std::popcount` since we're requiring C++20 anyway.

I think I get the basic idea.. in other words, let's say it's a medium complexity map with 10K portals. You're calculating visibility for leaf "A". With this PR, you periodically test all 10K portals against the current information for A and hopefully mark a lot of them as "definitely not visible from A", so you can hopefully do less recursive search?

For both @Paril and I, we're kind of limited in that we don't really understand the `vis` code... We sort of get the high-level idea, at least in 2D (e.g. https://fabiensanglard.net/doom3/dmap.php - the "History" heading + the Abrash video clip linked there) but how exactly that relates to `RecursiveLeafFlow` and how it maps to 3D we don't really understand. So our edits to the vis code have mostly been refactoring, postprocessing, etc.

Currently I'm working on adding some visualization of the visdata to `lightpreview` (which is our BSP viewer / compiler frontend - it runs all of the qbsp/vis/light code in process and renders the output).

I'm not too worried about having a test suite before merging this, I just want to finish my visdata renderer fly around a few maps while toggling this on/off to get more confidence about it. So don't feel you have to work on tests, but if you're interested, that's welcome too (we have just one vis test in `test_vis.cc`. The strategy I've been using for writing tests is mostly, compile a test map and check some properties of the resulting bsp file.)

**Comment by Paril** [comment]
There's a good video by kipi that describes the actual process for the clipping, which has helped greatly in my understanding of how this functions - basically how it can tell visibility by taking one portal and then clipping visibility down through all of the portals between the destination. I assume this change was mostly to fix the potentially unnecessary clip tests between long chains of portals that haven't been executed yet. Not certain.

I don't think we need an actual committed test suite, but we do need to run this on some known good maps to ensure that we don't introduce very obvious missing areas. I'm not as concerned about false positives, but we can't have any false negatives.

**Comment by ericwa** [comment]
> There's a good video by kipi that describes the actual process for the clipping, which has helped greatly in my understanding of how this functions - basically how it can tell visibility by taking one portal and then clipping visibility down through all of the portals between the destination.

Assuming this one - https://www.youtube.com/watch?v=IfCRHSIg6zo - just watched, yeah, super helpful. The "separators" and "source"/"pass"/"target" make sense now. It's more complex than I thought..

**Comment by rrika** [comment]
I worked through one example here:
photo_2023-08-04_13-58-13
The far X portal is never visible, but it only becomes apparent when reaching leaf 10, and there are many different paths towards 10. The upper half of the table below is a trace of the unmodified algorithm. A row like `Path: 0 A P D 5   Checks: E T` means that two clips are performed:
source=A pass=D target=E, and
source=A pass=D target=T. 
The × indicate a leaf is not visible according to the mightsee set. Orange background indicates a leaf has been visited at least once. Recursion only happens when there is any white cells left, that is, leafs that are potentially visible and have not been visited yet. In the rows with light blue background (13, 14, 15, 18, 19, 22, 23, 24) the leaf 11 past the X portal is the only thing keeping the recursion going, all other leafs are either not visible or have already been visited. These are the ones this patch tries to avoid.
trace
So, annoyingly it doesn't actually pay off to do target checks here, but suppose they are still triggered at step 22 because the number of source/pass/target checks performed so far (21) exceeds some threshold:
Nothing happens at step 22-1 because there is a source but no pass portal. At step 22-2 there is source=A pass=P and a list of target portals (D,E,S,T,U,F,G,H,X) derived from the current mightsee set (4, 5, 6, 7, 8, 9, 10, 11). A and P don't give useful separators, so nothing is culled. Next, at 22-3, source=A and pass=S and 3 out of 4 portals can be culled (giving new × for leafs 9, 10, 11). At 22-4 nothing is left to do. In theory this is better because the unreachability of X is now shown for all paths with prefix A P S, rather than one specific path. But there were only two paths left in that execution anyway, so we traded 2 checks for 13 checks.

**Comment by rrika** [comment]
oh, good news, I have made further improvements that make target checks a net positive for all three tested map sizes. ad_dm5 runtime drops to 37 minutes:
Screenshot_2023-08-06_00-51-50

when writing the previous comment I realized that there was no reason to group 22-1, 22-2, 22-3, 22-4 as one work unit. by doing each line individually, the target checks can be started sooner (since their predicted cost is lower) and their results applied sooner. I'll push an update to the branch soon.

**Comment by Paril** [comment]
I like the explanation but it's still hard for me to imagine what exactly it's doing, heh. After I get back from Quakecon I'll give this a test.

**Comment by ericwa** [comment]
Cool, thanks for the paper example, I will work through that!

Also while not directly related to this PR, I wanted to mention this issue which is still unfixed 
https://github.com/ericwa/ericw-tools/issues/263 where I inadvertently caused a huge (2x-3x) slowdown in vis while trying to fix another issues https://github.com/ericwa/ericw-tools/issues/261 . Very thin leafs were causing false negatives in the visdata (ie you'd get HOM's/"grey flash" in the middle of a room sometimes).

The patch https://github.com/ericwa/ericw-tools/commit/74e1a0f6f02a2a469ebf6d7c05c175096cfe01a3 fixed the problem but with a huge slowdown, so I assume it must be running the entire vis process multiple times or something.

So if you're seeing weird behaviour or performance numbers that are unexpectedly slower than other tools, it's probably that.

**Comment by rrika** [comment]
regarding #261: in the case all vertices of tp fall between -epsilon and epsilon, the two portal normals can be used to disambiguate an almost parallel portal or a coplanar one (reject when negative dot product between normals). if modifying the PRT format is acceptable then qbsp could write out the plane id for each portal, which might be even more accurate

**Comment by Paril** [comment]
modifying the PRT format is rough since a lot of tools rely on the format we have in place currently.. not impossible, but avoiding it is probably best.

**Comment by rrika** [comment]
This is blocked on #370, as perf numbers without that patch are kind of meaningless.

**Comment by rrika** [comment]
tonight I'll rebase/cleanup and remeasure and revalidate (preliminary result: 10min -> 5min for ad_dm5)

**Comment by rrika** [comment]
I only did a quick noclip flight around ad_dm5 but everything seems to work, and it does still help with vis times. I must've done my initial benchmarks on debug builds, switching to release and with the latest improvements the baselines (0.0) are much better.
Screenshot_2023-11-26_21-09-00

**Comment by ericwa** [comment]
This looks great, thanks!

I pushed a small adjustment to fix a perf regression I was seeing on this branch when `-targetchecks` is 0, so when all the new code is disabled. Apparently all the `std::popcount`'s were adding up to a 20% slowdown (at least on the map I'm benchmarking, `gmsp3v2.bsp`), so I just moved them inside a branch that doesn't execute unless we're using `-targetchecks`.

Also just adjusted the condition for calling `IterativeTargetChecks` to be a bit more obvious that it only runs if `vis_options.targetratio.value()` > 0.

I think it's good to merge and we should turn it on by default, does 0.5 make sense as a default?

That was the best out of 0, 0.5, and 1 on my test case:
```
gmsp3v2.bsp, -targetchecks 1.0: 14.2s
gmsp3v2.bsp, -targetchecks 0.5: 10.6s
gmsp3v2.bsp, -targetchecks 0: 18.2s
```

If my commits look OK I can go ahead and merge this.

**Comment by rrika** [comment]
I don't know what your release plans are, but I can provide a version of this for the original branch too (not brushbsp)

**Comment by ericwa** [comment]
Thanks. I don't think I'll do more releases of the old branch, we're committed to the `brushbsp` branch at this point (should probably rename it to `main` sometime) since the last 2 or so years of work all happened on `brushbsp`, and it has a test suite, "lightpreview" GUI, Q2 support, etc. So the plan is more `2.0.0-alphaX` releases and then `2.0.0-rc1` etc. as it stabilizes more.

**Pull request merged**
