### PR TITLE
Fix embree4 bitrot

### LINKED ISSUE #428: 2.0.0-alpha8 fails to build with embree4
Ubuntu 24.04 ships with embree4 (haven't checked if it has the same performance degradation as previous Ubuntu embree builds), and it seems there has been some bitrot in the embree4 code. Can fix a PR unless someone beats me to it.

Github Actions also provide 24.04 now, so probably a good idea to add that to the build matrix.

### PR DESCRIPTION
**Pull request by dsvensson**
Fixes #428

### CODE REVIEW

**Comment by dsvensson** [comment]
...except that it also hits a test failure it seems.

**Comment by ericwa** [comment]
Thanks. I'll see if I can repro the Ubuntu 24.04 + Asan error.

**Comment by ericwa** [comment]
I couldn't repro the Asan failure. However, on my local system I was using Ubuntu 24.04 (under WSL) + distro copies of TBB + Embree 4.

I checked the failing Ubuntu 24.04 CI logs, and there, it's still downloading Embree 3 + a binary package of TBB. So I'm trying adjusting that to make it use the distro copy of TBB + Embree

**Comment by ericwa** [comment]
Fixed the ASan error (it was related to a .wad in the test suite having a 16-character long texture name) and merged in 8ac82b7c79dafc9e409dbb4ada947cd0a3d85613

Thanks!

**Comment by dsvensson** [comment]
Oops... my bad missed what the CI used :)

**Pull request closed without merging**
